---

# Debian family install tasks

- name: 'INSTALL | APT | Remove packages'
  become: True
  apt:
    name: "{{ item.name }}"
    state: 'absent'
    cache_valid_time: "{{ base_packages_repository_cache_valid_time }}"
    update_cache: True
  loop: "{{ base_packages_items }}"
  when: "item.state | default('present') == 'absent'"


- name: 'INSTALL | APT | Install packages'
  become: True
  apt:
    name: "{{ item.name }}"
    state: 'present'
    cache_valid_time: "{{ base_packages_repository_cache_valid_time }}"
    update_cache: True
  loop: "{{ base_packages_items }}"
  when: "item.state | default('present') == 'present'"
